[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn --workers 1 --threads 4 --timeout 120 app:app"
healthcheckPath = "/ping"
healthcheckTimeout = 300
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 3
